### ISSUE TITLE
✨ Feature - HTML Rule preset configurations for different frameworks

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#365]
Hi @tombui99
  
### Pain
For SSW.Rules, Most of the HTML errors and warings are complaining about the generated HTML from our React pages. Developers have limited control over the generated code style.
For this reason, I have disabled a lot of the HTML rules. 

### Suggested Solution
Have preset configurations for different frameworks so I can pick React and get the correct configuration

![image](https://user-images.githubusercontent.com/38869720/181701238-6018b7f3-ddd5-4fa0-ba8a-28cde8b930ee.png)
**Figure: Possible location to select config**

### Tasks
```[tasklist]
### Todos
- [x] Discuss best UI/UX design with @tiagov8
- [x] Get mockup approved
- [x] Implement solution
- [ ] Record Done Video
- [ ] Gold plating - Would it be possible to detect the type of site automatically?
```

Thanks!

**Comment by tiagov8** [comment]
Hi @tombui99 

1. Please add another checkbox called "React project" next to "Select All"
2. Clicking on it should disable the necessary Rules (the ones manually disabled by @bradystroud)
3. Please also change from
    **Enabled Rules:**
    to
    **Enable/Disable Rules**

**Comment by tombui99** [comment]
Hi @bradystroud 
cc @tiagov8 

Can you help list all the custom rules you would want to enable for specific React projects?

Thanks a lot

**Comment by zacharykeeping** [comment]
Hey @BrookJeynes 

- [ ] Would you be able to provide a list of rules to enable/disable that are relevant to React projects?

Thanks!

**Comment by BrookJeynes** [comment]
CC: @tiagov8 

(Checked by @bradystroud)

Hey @zacharykeeping 

\> Would you be able to provide a list of rules to enable/disable that are relevant to React projects?

![Figure: Checks to turn off](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/25432120/e7c7c1ba-600e-44c3-bdc2-72138ef7307d)
**Figure: Checks to turn off**

This is not a good solution - These errors are mostly caused by Gatsby. However, turning these off completely will cause developer made issues to be ignored.

The better solution would be to have Code Auditor scan through the source code itself rather than the HTML output which is manipulated via Gatsby and others.

**Comment by zacharykeeping** [comment]
> 1. Please add another checkbox called "React project" next to "Select All"
>2. Clicking on it should disable the necessary Rules (the ones manually disabled by @bradystroud)
>3. Please also change from
Enabled Rules:
to
Enable/Disable Rules

Done all - there's now a React preset with the above rules, and the wording for the modal has been updated.

<img width="1158" alt="Screenshot 2023-08-14 at 12 20 15 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/9affe94f-679c-492c-940d-f37a34f4a996">

**Figure: New React preset**

**Comment by zacharykeeping** [comment]
> Record Done Video

Done - I've recorded a quick Done Video for this feature here: https://youtu.be/Zdjh35QzwiE
