### ISSUE TITLE
✨ Install Google Analytics 4 to CodeAuditor site

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#368]
Cc: @hveraus @adamcogan 

---

Hi @tombui99 
  
### Pain
We are not currently getting data from CodeAuditor into Google Analytics

### Solution
Install Google Analytics

```
<!-- Google tag (gtag.js) GA4 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-H60LQX43P9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-H60LQX43P9');
</script>
```

### Tasks
1. [x] Add the script pasted above to the <head> of the site 
2. [x] Once task 1 is done, tell Tiago via Teams to test it is generating hits
3. [x] Once task 2 is confirmed, tell Ken to update the GA4 report

Thanks!

---

This task is regarding this email thread: **Re: Google Analytics 4 data - let's get it right**

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

> Add Google Analytics 4 to CodeAuditor site
Once task 1 is done, tell Tiago via Teams to test it is generating hits
Once task 2 is confirmed, tell Ken to update the GA4 report

All done - I have added GA 4 to CodeAuditor, had it tested by Tiago and got Ken to update the GA4 report

Thanks,
Tom

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

Closing this issue as it has been done
