### ISSUE TITLE
🐛  Syntax - special characters must be escaped - Not sure how to fix

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#405]
Cc: @adamcogan 

Hi @tombui99 

### Describe the Bug
This warning is weird. I see nothing wrong with the code. But CodeAuditor points to this https://htmlhint.com/docs/user-guide/rules/spec-char-escape

Have a look at the rule markdown/markup https://ssw.com.au/rules/use-icons-to-not-surprise-users/
I can't see any special characters that need fix

The `<a>` tag is inside a `<code>` tag so it should trigger any error... but the `<` was reported as error

My concern is that we will have hundreds of `<` and `>` signs inside code examples everywhere... CodeAuditor caught this one as an error, but not the rest. The main example is the "greater than sign" `>` right after the a. Not caught...

Not sure how CodeAuditor got the "less than sign" as a special character nor what it expects to be fixed.

Page: https://raw.githubusercontent.com/SSWConsulting/SSW.Rules.Content/main/rules/use-icons-to-not-surprise-users/rule.md

<img width="1131" alt="Screen Shot 2023-01-07 at 4 05 43 PM" src="https://user-images.githubusercontent.com/12601228/211174852-ed768759-9e9e-46da-82fb-45ae7fe717c3.png">
<img width="733" alt="Screen Shot 2023-01-07 at 4 07 42 PM" src="https://user-images.githubusercontent.com/12601228/211174854-7c461371-5ec7-48c7-9ae8-923dfcc12cd4.png">

### Tasks
- [ ] Investigate what triggered the warning
- [ ] Let us know what is needed OR fix

Thanks!

**Comment by tiagov8** [comment]
Hi @tombui99 

as per our conversation on Teams, we agreed it's best to disable the default rule and create a new one that says we don't want characters that are in the HTML syntax inside content.

1. Please action
2. Make sure that if the character is inside a <code> tag, then it is obvisouly good to go
3. Run a report after implemented to confirm the error reported above is not been shown anymore

**Comment by tombui99** [comment]
Hi @tiagov8
cc @adamcogan 

    > Add a new rule to check for special characters and make sure that if the character is inside a <code> tag, then it is obviously good to go

Done 

![image](https://user-images.githubusercontent.com/67776356/213056012-1814e6ff-b26f-4be6-a04a-9c364352e2b6.png)
**Figure: New custom rule for checking special HTML characters**

![image](https://user-images.githubusercontent.com/67776356/213056059-45387c51-4bc1-49f0-84af-300b47f530f9.png)
**Figure: The code block logic to check for special character**

![image](https://user-images.githubusercontent.com/67776356/213056106-335548a1-7b55-4593-93ad-56768d0bf3b2.png)
**Figure: Unit test cases with good and bad examples**

![image](https://user-images.githubusercontent.com/67776356/213056130-0c562f05-3af0-4856-b118-0017602ec061.png)
**Figure: All test cases have been passed**


  > Run a report after implemented to confirm the error reported above is not been shown anymore

Done - I have ran a new scan with the new custom rule enabled and the false positive error mentioned does not appear anymore
https://codeauditor.com/build/1fbff3e7-9552-4f0e-329c-a22bf05a8a54

![image](https://user-images.githubusercontent.com/67776356/213056219-372253b4-66c2-409b-b7d1-17352fc3e66b.png)
**Figure: Latest SSW Rules scan report**

![image](https://user-images.githubusercontent.com/67776356/213056235-1c51e9ce-2996-4005-bc1f-6219bd9c1461.png)
**Figure: List of reported HTML errors on SSW Rules does not show the new custom rule**

**Comment by tiagov8** [comment]
Ho @tombui99 

I didn't expect this rule to not return any result. We have hundreds of old rules, I assumed some would have some HTML character in the content here and there. 

I went to archived rules and found this one that as an example of HTML in content https://ssw.com.au/rules/do-you-know-how-to-custom-styles-for-richhtmleditor-in-sharepoint-2013/ 

1. How to make sure the rule is actually working?

Cheers,

**Comment by tombui99** [comment]
Hi @tiagov8 

> How to make sure the rule is actually working?

To make sure the rule is working, I have written unit test with all the possible cases of correct and incorrect syntax and the custom rule has passed all of the cases.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/67776356/228737993-24176a5b-8d19-4621-aaf4-80e241bcfd43.png">

**Figure: All unit test cases**

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

Closing issue as question has been answered.

Feel free to re-open if it's still unclear

**Comment by tiagov8** [comment]
Hey @tombui99 

(reopening as the latest report caught the same bug)

This rule https://ssw.com.au/rules/use-icons-to-not-surprise-users/#how-to-add-icons-to-links-via-css 
...has a piece of code `<a>` that was caught by CodeAuditor. Itr shouldn't

- [ ] Please investigate and fix

<img width="1142" alt="Screenshot 2023-04-04 at 6 37 25 PM" src="https://user-images.githubusercontent.com/12601228/229928884-6d1af012-e39e-4b3b-a46f-02e0c4c96884.png">

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan @william-liebenberg 

> Please investigate and fix

From the latest scan, this false positive is no longer reported as CodeAuditor is no longer checking any special characters in the `code` tag.

See https://codeauditor.com/htmlhint/c89dca20-12fa-4392-37e6-3652729173c3?displayMode=1

> The piece of code doesn't actually have a special character in Markdown NOR on Chrome Inspect. Only CodeAuditor read it as &#x3C;a>. It's especially weird because only the lesser than sign is wrong, the greater than is fine.

This seems to be an issue with the rendered HTML rather than CodeAuditor. If you look into the page source of the page, it actually reads the less sign as `&#x3C;a>` and CodeAuditor was just scanning from this HTML page source.

![image](https://user-images.githubusercontent.com/67776356/233287562-41e97f0b-c0a1-482b-87f3-3eb82f38d40a.png)

**Figure: Page source from the SSW Rule**
