### ISSUE TITLE
♻️ UI - Improve CodeAuditor Rules page view

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#421]
Cc: @adamcogan 

Hi @tombui99 

### Pain

https://codeauditor.com/rules is inconsistent with SSW styling

<img width="734" alt="Screenshot 2023-04-03 at 10 14 47 AM" src="https://user-images.githubusercontent.com/12601228/229522407-614a039b-1038-4ccf-8380-cb1b311f7faf.png">

### Tasks

- [x] Remove the blue (links should be inherit color underlined + red on hover). See https://ssw.com.au/rules/rule/#4-links as reference
- [x] Change the lists from "`1 :  XXX`" to "`1. XXX`"
- [x] Make the first letter after all prefixes Capitalized. From "`Tags - tag names...`" to "`Tags - Tag names...`"
- [x] Increase 4x the padding between the sections headings. It's too close to the list above
   
   <img width="575" alt="Screenshot 2023-04-03 at 10 28 13 AM" src="https://user-images.githubusercontent.com/12601228/229524054-b50dae3d-806d-4081-a741-bc320e8d3718.png">

- [x] I think "SSW Rules" could come 1st, before "HTMLHint Rules"...

- [x] Action the email **"Re: CodeAuditor - Rename custom rules' titles"**

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

> Improve CodeAuditor's Rules page view

All done - the page has been updated as requested and I have also replied to email "**Re: CodeAuditor - Rename custom rules' titles**"

![image](https://user-images.githubusercontent.com/67776356/232682406-74bc2a5c-0a81-4778-9bd4-1e845f4802a2.png)

**Figure: Updated Rules page view**
