### ISSUE TITLE
📝 Custom HTML Rules - Missing related SSW Rules 

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#428]
Cc: @adamcogan @william-liebenberg 

Hi @tiagov8 

### Pain

As per our conversation, there are missing SSW Rules for some of our custom HTML rules.

Please find below the HTML rules that need their related SSW Rules:
1. Content - Use Unicode Hex code for special HTML characters
2. Links - URLs must not include full stop or slash at the end
3. Links - Detect absolute internal URLs
4. Links - URLs must not have UNC paths

There is also a custom rule that is currently using an external site
1. [Header - Must not refresh or redirect](https://rules.sonarsource.com/html/RSPEC-1094)

### Tasks

Create new SSW Rules for:
- [x] 1. Content - Use Unicode Hex code for special HTML characters
- [x] 2. Links - URLs must not include full stop or slash at the end
- [x] 3. Links - Detect absolute internal URLs
- [x] 4. Links - URLs must not have UNC paths

Thanks!

**Comment by tiagov8** [comment]
> 4. Links - URLs must not have UNC paths

Done - https://www.ssw.com.au/rules/urls-must-not-have-unc-paths/

**Comment by tiagov8** [comment]
> 2. Links - URLs must not include full stop or slash at the end

Done - https://ssw.com.au/rules/no-full-stop-or-slash-at-the-end-of-urls

---

Hey @tombui99 

1. Please change from

**Links - URLs must not include full stop or slash at the end**

to

**Links - URLs should not include full stop or slash at the end**

**Comment by tombui99** [comment]
Hi @tiagov8 

> Links - URLs must not include full stop or slash at the end
to
Links - URLs should not include full stop or slash at the end

Done - I have renamed the rule name

**Comment by tiagov8** [comment]
>  3. Links - Detect absolute internal URLs

Done - https://ssw.com.au/rules/avoid-absolute-internal-links

---

Hey @tombui99

Please change from
Links - Detect absolute internal URLs

to

Links - Avoid absolute internal URLs

**Comment by tombui99** [comment]
Hi @tiagov8 

> Renamed to Links - Avoid absolute internal URLs

Done - I have renamed the custom rule title

Please let me know if you need any further changes :)

**Comment by tiagov8** [comment]
>  1. Content - Use Unicode Hex code for special HTML characters

Done - https://ssw.com.au/rules/html-unicode-hex-codes

**Comment by tombui99** [comment]
Hey @tiagov8 

All done - I have added the missing rule links 

See https://codeauditor.com/rules
