### ISSUE TITLE
📝 Wiki - Create Knowledge Base (KB) for unscannable websites

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#429]
Cc: @william-liebenberg @tiagov8 

Hi @adamcogan 

### Pain

As per our conversation, there are websites that have anti web scraping mechanism that prevents CodeAuditor from scanning. Therefore, we need to create a KB by using GitHub Wiki for these unscannable websites. 

### Tasks

- [x] Read https://ssw.com.au/rules/do-you-have-a-knowledge-base-kb/
- [x] Implement by using the GitHub Wiki for the KB
- [x] Put that screenshot from CodeAuditor wiki on that rule + a link to it as an example

Thanks!

**Comment by tombui99** [comment]
Hi @adamcogan 
cc @william-liebenberg @tiagov8 

> Read https://ssw.com.au/rules/do-you-have-a-knowledge-base-kb/
 
Done

> Implement by using the GitHub Wiki for the KB

Done - created GitHub Wiki for the KB in CodeAuditor
See https://github.com/SSWConsulting/SSW.CodeAuditor/wiki/SSW-CodeAuditor-Knowledge-Base-(KB)

> Put that screenshot from CodeAuditor wiki on that rule + a link to it as an example

Done - Rule has been updated with provided screenshot as an example

See https://www.ssw.com.au/rules/do-you-have-a-knowledge-base-kb/
