### ISSUE TITLE
👷 DevOps - Retrieve and replace new token from service account for SSW projects scan  

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#430]
Cc: @william-liebenberg @adamcogan @bradystroud 

Hi @tombui99 
  
### Pain

As per my conversation with @bradystroud and @william-liebenberg, currently, all scheduled scans for SSW Rules, People, and Website in CodeAuditor are using my personal token. However, the token should be derived from the SSW service account instead.

### Tasks

- [x] Contact Sysadmins to acquire a SSW service account 
- [x] Generate new token derived from the service account
- [x] Replace all current token used for scheduled scans on SSW Rules, People and Website
- [x] #435

Thanks!

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg 

> Contact Sysadmins to acquire a SSW service account
Generate new token derived from the service account
Replace all current token used for scheduled scans on SSW Rules, People and Website

All done - I have added a new CodeAuditor account on SSW Keeper and use the token for all scheduled scans
