### ISSUE TITLE
♻️ UI - Improve unscannable links section

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#438]
Hi @tiagov8 

As per our conversation, our unscannable links section needs further UI improvement

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/67776356/235808613-f7bb1744-8bed-415a-ba89-6b57a05fd4e2.png">

**Figure: Current UI for unscannable links section**

### Tasks

- [ ] Please have a look and provide me feedback

Thanks!

**Comment by tiagov8** [comment]
- [ ] 1. Change from

    **Found Unscannable Links:**
    **See our [Knowledge Base (KB)](https://github.com/SSWConsulting/SSW.CodeAuditor/wiki/SSW-CodeAuditor-Knowledge-Base-(KB)#known-websites-that-has-anti-web-scraping-measures) to learn more about why some working websites are reported as broken in CodeAuditor?**

  to

    **Unscannable Links:**
    Some working links are reported as broken by CodeAuditor. They're marked as "unscannable". [Learn more on our KB](https://github.com/SSWConsulting/SSW.CodeAuditor/wiki/SSW-CodeAuditor-Knowledge-Base-(KB)#known-websites-that-has-anti-web-scraping-measures).

**Comment by tiagov8** [comment]
- [ ] 2. Please change CSS :

```
.link {
    border-bottom: 1px dotted #9e9e9e;
    background-color: transparent;
}
```

to

```
.link {
    text-decoration: underline;
    text-decoration-color: #aaa;
    text-decoration-style: solid;
    text-decoration-thickness: 1px;
    transition: color .25s ease;
    word-break: break-word;
}

.link:hover {
    color: #cc4141;
    text-decoration-color: #cc4141;
}

```

**Comment by tiagov8** [comment]
- [ ] 3. Please implement this design:

<img width="1170" alt="Screenshot 2023-08-07 at 4 13 04 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/5f524efb-dd6a-4d7a-8c93-3a9ad42b72b2">

HTML: https://codepen.io/tiagov8/pen/RwPwRMR

- [ ] 4. Please make sure all the inline CSS is in the CSS file as per https://www.ssw.com.au/rules/have-a-stylesheet-file/

- [ ] 5. Get it "Checked by Tiago" before publishing

**Comment by zacharykeeping** [comment]
All done - all the above tasks have been completed and the Unscannable Links UI has been updated.

<img width="992" alt="Screenshot 2023-08-16 at 10 24 18 am" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/76c481b2-0af7-4b58-8853-386a9f42cb93">

**Figure: Update Unscannable Links section**

**Comment by tiagov8** [comment]
Hey @zacharykeeping
Expected to see this closed once the changes are live... What is the ETA?

**Comment by zacharykeeping** [comment]
Hey @tiagov8 

Tom has deployed these changes so this should be live now.
