### ISSUE TITLE
✨ Scan comparison

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#471]
Cc: @william-liebenberg @adamcogan @BrookJeynes @tiagov8 

Hi @tombui99 
  
### Pain
As per our conversation, there is no way to see change in scans. 
e.g. If i fix some issues, I want to see "15 less broken links than last scan" somewhere

### Suggested Solution
The ablility to compare scans

### Tasks
- [x] Get any new UI from @tiagov8 
- [x] Add the feature
- [x] Get checked by @bradystroud and @BrookJeynes 

Thanks!

**Comment by tombui99** [comment]
cc @william-liebenberg @adamcogan @BrookJeynes @tiagov8 

Hi @bradystroud 

> Get any new UI from @tiagov8
 Add the feature
 Get checked 

All done - As per our conversation and with the designers, I have implemented this feature that lets user compare to latest scan

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/19734053-dabe-4ca9-8aa8-f29ecbd5f7e8)

**Figure: New "Compare to latest scan" button to go to scan comparison page**

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/b4db1f8b-1a2c-406c-9a00-40d345b5f287)

**Figure: New scan comparison page that lets user select and compare past to latest scan**
