### ISSUE TITLE
✨ Email - Ability to send report email after each scan 

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#481]
Cc: @william-liebenberg @adamcogan @BrookJeynes @bradystroud  

To Myself,
  
### Pain

As per my conversation with @bradystroud, @adamcogan would like to have an option to add participants who we would like to send an email to after each scan with reports of the numbers and comparison between past and latest scan.

### Suggested Solution

There should be an option in CodeAuditor UI that lets you add email addresses you would like to send to after each scan.

### Tasks

- [x] Add new section in the scan UI that lets user adds email addresses
- [x] After each scan, a report email to be sent to these email addresses
- [x] Add instruction to the Wiki and How It Works page
- [x] Ask desginers for UI feedback and improve

Thanks!

**Comment by tombui99** [comment]
cc @william-liebenberg @adamcogan @bradystroud @BrookJeynes 

> Add new button in the scan UI that lets user adds email addresses

Done - Added new button to add alerted email addresses

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/2e62c5f6-00b7-4fe7-afc1-f48bee4ed203)

**Figure: Button to open alert emails modal**

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/2a075ce2-02eb-4419-8312-54f36694579f)

**Figure: Modal to add or remove alerted email addresses**

> After each scan, a report email to be sent to these email addresses

Done - automated alert email is sent after each scan

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/6f345d27-461f-4465-ad4f-ea1939d883f1)

**Figure: Sample automated email alert**

> Add instruction to the Wiki and How It Works page

Done - new instruction added to Wiki and How It Works page

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/a05da40c-b92b-40c2-86fb-d573d6b52240)

**Figure: Instruction added to How It Works page**

> Ask desginers for UI feedback and improve

Done - designer feedback added as per https://github.com/SSWConsulting/SSW.CodeAuditor/issues/494
