### ISSUE TITLE
♻️ SSW.CodeAuditor homepage - Can we have an informative page?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#488]
Cc: @adamcogan 

Hi @tombui99 

### Pain
CodeAuditor homepage is not useful at all: https://codeauditor.com/home

It shows a scan which is kind of a poor version of the [Explore page](https://codeauditor.com/explore).

### What could be improved?

I suggest we:

1. Remove "Home" button from the menu
2. Make [How it works](https://codeauditor.com/howitworks) the homepage (as the 1st button) 

### Tasks

- [ ] Double check with Product Owner
- [ ] Action

<img width="1722" alt="Screenshot 2023-06-06 at 11 31 28 AM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/e1456043-6b4a-4d48-8363-592aac67b644">

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 

As per our conversation, we will need to do the following:

- [ ] Rename How it Works to Home 
- [ ] Then move it to be 1st
- [ ] Remove the current Home (Your Scans) since it's already under the username... which is a more intuitive location:

**Comment by tombui99** [comment]
Hi @tiagov8 

> Rename How it Works to Home
 Then move it to be 1st
 Remove the current Home (Your Scans) since it's already under the username... which is a more intuitive location:

All Done - I have updated our Navbar 

<img width="1315" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/316a9247-e4fd-4a7c-b1ad-2059208ae90a">
