### ISSUE TITLE
♻️ UI - Add new UI column to show how long a broken link has been around

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#531]
Cc: @adamcogan @william-liebenberg @tiagov8 

### Pain

As per my conversation with @adamcogan and @william-liebenberg , we should add a new UI section on the Scan Details page to show how long a broken link has existed (unfixed)

### Tasks

- [x] 1. In Scan Detail page, add new column to show the broken link's age (how long it has been there unfixed)
- [x] 2. In Scan Compare page, on the right, change from "9 Broken Links" to "9 Broken Links (4 Existing)"
- [x] 3. Get a test passed from @william-liebenberg 

### Screenshot
<img width="1257" alt="Screenshot 2023-07-16 at 3 56 48 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/e6d0b5ae-8661-48c6-8e72-eb216b6b76dd">

**Figure: Curren Scan Detail page**

Thanks!

**Comment by zacharykeeping** [comment]
Done all - links now show their age and the Compare Scans page now shows the count of existing broken links.

<img width="1242" alt="Screenshot 2023-09-13 at 2 03 05 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/01132831-8665-420c-b413-95226b19f874">

**Figure: Number of days a link is unfixed**

<img width="776" alt="Screenshot 2023-09-06 at 5 17 30 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/600d8d0f-92ec-4c00-a4ae-11223d371d5c">

**Figure: Updated right column to show existing broken link count**
