### ISSUE TITLE
🐛 Scheduled GitHub workflow run on SSW Website - Docker stuck when pulling image

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#547]
Cc: @adamcogan @william-liebenberg @Jord-Gui @zacharykeeping @wicksipedia @bradystroud 

### Describe the Bug

As from @wicksipedia email, when SSW Website's GitHub Action ran CodeAuditor over the weekend, Docker was stuck when pulling the image for 6 hours until @wicksipedia cancelled the workflow with the following error.

<img width="668" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/bc53711f-b325-42ef-aa79-cade196140b6">

**Figure: error when pulling docker image**

When manually rerunning the GitHub Action workflow again, the run was successful. 

### Tasks
- [x] Investigate and fix the error on GitHub Action
- [x] Fix Artillery Load Test failing on SSW Website

Thanks!

**Comment by wicksipedia** [comment]
@tombui99 when I looked at the logs <https://github.com/SSWConsulting/SSW.Website/actions/runs/5636667732/job/15268953512> - the image pull was successful but there was an argument error in the command, then nothing.

When you re-ran the job, there is still an argument error

**Comment by tombui99** [comment]
> @tombui99 when I looked at the logs https://github.com/SSWConsulting/SSW.Website/actions/runs/5636667732/job/15268953512 - the image pull was successful but there was an argument error in the command, then nothing.
> 
> ![CleanShot 2023-07-24 at 15 37 51@2x](https://user-images.githubusercontent.com/600044/255492128-85777067-903b-45f3-9ca8-ee1e32632d7d.png)
> 
> When you re-ran the job, there is still an argument error but it executed the job
> 
> ![CleanShot 2023-07-24 at 15 37 37@2x](https://user-images.githubusercontent.com/600044/255492230-d0e65a2f-6194-4d71-8bc2-4e2c34ef0204.png)

Thanks @wicksipedia , I have updated the Issue's description with the error

**Comment by tombui99** [comment]
Hi @wicksipedia 
cc @adamcogan @william-liebenberg @Jord-Gui @zacharykeeping @bradystroud 

> Investigate and fix

Done - This error was caused by GitHub dependabot updating Artillery Load Test to latest version that introduced breaking changes. This is now fixed by downgrading Artillery package from version `2.0.0-34` to `1.7.9`

See https://github.com/SSWConsulting/SSW.Website/actions/runs/5636667732 - Latest run is now successful without any error message

<img width="882" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/f7297890-64de-4411-96a1-1e52d757784d">

**Comment by wicksipedia** [comment]
> Latest run is now successful without any error message

I'm assuming that the error message in the screenshot is expected? If yes, then the screeenshot is confusing - I'd recommend catching the error and showing a better message

**Comment by tombui99** [comment]
>I'm assuming that the error message in the screenshot above is expected? If yes, then the screeenshot is confusing - I'd recommend catching the error and showing a better message

Hey @wicksipedia , after some testings, this error was caused by Artillery Load Test failing to run on SSW Website. However, it is working just fine on SSW Rules, People and other tested sites so I believe there must be something to do with SSW Website's cookie setting.

I will work and discuss this further with @amankumarrr to find a solution.

**Comment by wicksipedia** [comment]
@tombui99 - still an issue

https://github.com/SSWConsulting/SSW.Website/actions/runs/5706436754/job/15462114666

**Comment by tombui99** [comment]
> @tombui99 - still an issue
> 
> https://github.com/SSWConsulting/SSW.Website/actions/runs/5706436754/job/15462114666

Hi @wicksipedia, as per my conversation with @Harry-Ross , he will investigate SSW Website's Cookie setting to see if it has been set in the HTTP-Header. I have created a new issue in SSW Website 

See SSW Website issue https://github.com/SSWConsulting/SSW.Website/issues/1146

**Comment by bradystroud** [comment]
cc @Harry-Ross @wicksipedia @Jord-Gui 
Hey @tombui99 

I think the Artillery load test failing should be a new issue, seperate to the docker image not pulling.
CodeAuditor should be able to be added to any site without much pain, it is inconvenient to configure cookie settings.
If cookie setting changes are required, CodeAuditor should provide a useful error message that links to some docs that explain how to fix it.

> This is now fixed by downgrading Artillery package from version 2.0.0-34 to 1.7.9

Downgrading a package is not a permanent solution, please investigate  further.

- [ ] Split up these issues
- [ ] Do we really need to configure cookies? If yes, document it and improve the error message
- [ ] Investigate the Artillery package more

**Comment by tombui99** [comment]
Hey @bradystroud 
cc @Harry-Ross @wicksipedia @Jord-Gui @william-liebenberg 

> Split up these issues
 Do we really need to configure cookies? If yes, document it and improve the error message
 Investigate the Artillery package more

Done - I have added a new issue regarding Artillery load test failing on SSW Website and that CodeAuditor should be able to provide useful error message with documentations how to fix it

See https://github.com/SSWConsulting/SSW.CodeAuditor/issues/560
