### ISSUE TITLE
♻️ UI/UX - Improve Homepage images & Footer section

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#553]
Cc: @adamcogan @william-liebenberg @tiagov8 @Jord-Gui @zacharykeeping 

### Pain

As per my conversation with @tiagov8 , we need to make the following UX improvements

### Tasks

- [x] On the footer:
Change from 
`FEEDBACK TO SSW`
to
`FEEDBACK TO SSW CODEAUDITOR`

- [x] Update the link to T&C (avoid redirect) HOMEPAGE https://codeauditor.com/home:
Change from
`https://www.ssw.com.au/ssw/Standards/Forms/ConsultingOrderTermsConditions.aspx`
to
`https://www.ssw.com.au/terms-and-conditions`

- [x] Homepage - copy the style for images from SSW.Rules - have a little padding and a light grey background. This will improve readability
![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/444e8010-009f-41c6-a470-a9b06215507d)
**Figure: SSW Rules image with gray border padding**
- [x] Copy the Footer style from [SSW Rules](https://ssw.com.au/rules/)
![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/e53f82c4-d011-45bc-8fae-87f0812104de)
**Figure: SSW Rules footer**

Thanks!

**Comment by Jord-Gui** [comment]
Done - change from 'FEEDBACK TO SSW' to 'FEEDBACK TO SSW CODEAUDITOR'

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/569ce8d4-1835-4a15-abb2-412174f5c57d)
Figure: updated footer

**Comment by tiagov8** [comment]
Hey @tombui99 

I think we better do as Rules:

from

**FEEDBACK TO SSW CODEAUDITOR**

to

**FEEDBACK / SUGGEST A FEATURE**

**Comment by Jord-Gui** [comment]
Done - Footer has been changed and images now have gray border around them
![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/1494363e-73c8-494e-bcf3-69ffcc9939f5)
Figure: improved footer section
![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/32fd45f6-481e-4e75-bdd0-a8a3d3774358)
Figure: gray border around an image
