### ISSUE TITLE
📝 Rule - Create a new SSW Rules for using GitHub variables with special characters

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#563]
Cc: @bradystroud @william-liebenberg @adamcogan @Jord-Gui @zacharykeeping @tiagov8 
 

### Pain

We should write a new SSW Rules about using GitHub secrets or variables that contain special characters to avoid issues such as escaping characters.

### What code could be improved?

We need to write a new GitHub rule on SSW Rules on this matter

### Tasks

- [x] Write a new GitHub rule about using variables that contain special characters (go straight to GitHub i.e., don't use Netlify editor)
- [ ] Buzz @william-liebenberg  to get it reviewed and which section to place it
- [ ] Get it checked by @bradystroud and @tiagov8 

Thanks!

**Comment by zacharykeeping** [comment]
Done - this rule has been created here:

https://www.ssw.com.au/rules/handle-special-characters-on-github/
