### ISSUE TITLE
♻️ UI - Ask designers for feedback to make Homepage more readable

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#564]
Cc: @bradystroud @william-liebenberg @adamcogan @Jord-Gui @zacharykeeping @tiagov8 @jaydenalchin
 

### Pain

Our homepage UI could be improved to make the features and its figures more readable and user friendly.

### What code could be improved?

We should ask the designers for feedback on how we can improve it so CodeAuditor will look more appealing to new users.

### Tasks

- [ ] Ask designers for homepage UI feedback and get new mockups (@tiagov8 @jaydenalchin @2fernandez)
- [ ] Implement the UI changes

Thanks!

**Comment by zacharykeeping** [comment]
Hey @tiagov8 
cc: @jaydenalchin 

- [ ] Can you please provide some feedback for our homepage UI and provide some mockups for how it can be improved?

Thanks!

**Comment by tombui99** [comment]
cc @zacharykeeping @Jord-Gui @william-liebenberg @adamcogan @bradystroud 

As per my conversation with @jaydenalchin , we should change the header to look like the one in https://sugarlearning.com/

- [ ] Implement change
- [ ] Get it checked by @jaydenalchin 



![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/959b1188-4b86-4a66-8c6e-7825291bbf8f)

**Comment by zacharykeeping** [comment]
Done - the new header design has been implemented.

<img width="1280" alt="Screenshot 2023-08-25 at 4 08 23 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/f39de64d-b974-4e60-b4eb-7c7eb595be42">

**Figure: Updated header design**

**Comment by tiagov8** [comment]
Hey @zacharykeeping 

When will this be in PROD?

I'd suggest giving the login button the 1px border for consistency

Cheers,
