### ISSUE TITLE
✨ Feature - Determine a new feedback loop to raise alerts when a number of broken links goes up

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#565]
cc @adamcogan @william-liebenberg @zacharykeeping @Jord-Gui @bradystroud 

CodeAuditor should be able to create new issue whenever the number of broken links or code errors/warnings increases.

See example how to create issues using GitHub CLI https://github.com/william-liebenberg/hotfixer/blob/main/.github/workflows/hotfix-pp-to-prod.yaml#L80

### Tasks

- [x] Create a GitHub workflow template that creates new issues when errors go up
- [x] Add more details to the generated GitHub issues (errors count, scan details link)
- [x] Publishing the actions in GitHub Marketplace. See https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace
- [x] Add errors status (up or down) in Job Summaries
- [x] #706
- [x] #705
- [x] Make the Codeauditor token secret in example usage
- [x] Create a done video
- [x] Get it checked by @william-liebenberg

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg @zacharykeeping @Jord-Gui @bradystroud 

> Create a GitHub workflow template that creates new issues when errors go up

Done - created a working GitHub workflow template that creates new issues whenever errors go up

See https://github.com/tombui99/test-github-workflow/blob/main/.github/workflows/main.yml

**Comment by bradystroud** [comment]
Hey Tom, is this enabled on any of our repos?

Also, looks like there are a bunch of tasks that haven't been done yet

**Comment by tombui99** [comment]
> Hey Tom, is this enabled on any of our repos?
> 
> Also, looks like there are a bunch of tasks that haven't been done yet

Hey @bradystroud 

> is this enabled on any of our repos

No it's not, I've only created an initial working template but still requires further adjustment from William's feedback during last Sprint therefore this item is still marked as "In Progress"

**Comment by tombui99** [comment]
As per our conversation with @wicksipedia , these are the improvements we need to make before publishing this workflow to GitHub Marketplace:

- [ ] README - Add a section to introduce what CodeAuditor is, what it does, etc.
- [ ] README - Add Best practices section on how to setup and use
- [ ] README - Remove `actions/checkout@v3` step from the example workflow
- [ ] README - Add prerequisite section to check if the site has been deployed in order to run CodeAuditor scan
- [ ] README - Add details on how user can run docker scan locally (TBD)
- [ ] Workflow - Use Action token instead of GitHub Personal token by giving the action write permission  
- [ ] Get someone who has never used CodeAuditor before to check
- [ ] Rename the workflow title for clearness

**Comment by tombui99** [comment]
- [ ] Put token and site urls in github environment vars
- [ ] Rename to: ssw/codeauditor-scan-site@v1.0.0
- [ ] add option: enable-raise-pr
- [ ] add job summaries: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

 

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg @zacharykeeping 

> README - Add a section to introduce what CodeAuditor is, what it does, etc.
README - Add Usage and Best practices example section on how to setup and use
README - Remove actions/checkout@v3 step from the example workflow
README - Add prerequisite section to check if the site has been deployed in order to run CodeAuditor scan
README - Add details on how user can run docker scan locally (TBD)
Workflow - Use Action token instead of GitHub Personal token by giving the action write permission
After some investigations, GitHub CLI cannot create issue without GitHub Tokens
Rename the workflow title for clearness
Put token and site urls in github environment vars
Rename to: ssw/codeauditor-scan-site@v1.0.0
Add job summaries

All done - the workflow has been created under SSWConsulting and released to GitHub Marketplace
See https://github.com/marketplace/actions/codeauditor-workflow

**Comment by tombui99** [comment]
- [ ] Implement the workflow on SSW Rules, People and Website once approved
- [ ] Get it checked by @william-liebenberg
- [ ] Create a done video

**Comment by bradystroud** [comment]
cc @will iam-liebenberg 
Hey @tombui99 

This one doesn't look complete, can you please double check?

**Comment by will** [comment]
I dont have much context here sorry

**Comment by tombui99** [comment]
Hey @bradystroud 

Sorry my bad, still got few items left to do. 

I'm reopening the issue.
