### ISSUE TITLE
✨ Ability to report and ignore false positives on a scan

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#576]
Cc: @BrookJeynes @adamcogan @william-liebenberg @bradystroud @zacharykeeping @Jord-Gui 

  
### Pain

As per my conversation with @BrookJeynes , we should add a flagging option to CodeAuditor's scans that let user flag an item as "False Positives". 

We should also enable user to ignore url per custom Rules to avoid scanning for false positive in the following scans.

### Suggested Solution

User should be able to flag an item on a scan as "False Positive" - This would allow user to notify themselves or whoever is working on CodeAuditor that the scan has picked up a false positive

User should also be able to ignore Urls that contain false positive custom rule so it will not be scanned in the next run.

### Tasks

- [x] Implement a flagging feature to flag for "false positives" 
- [x] Implement an input option in each custom rule to ignore checking it in certain Urls
- [ ] Ask designers for UI feedback ( @tiagov8 or @jaydenalchin )
- [x] Create a new done video and have it checked by @william-liebenberg and @adamcogan 

### Screenshots

Thanks!
