### ISSUE TITLE
♻️ UI - Indicate 0 errors in the graphic preview scan

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#602]
Cc: @adamcogan @zacharykeeping 

Hi @tombui99 

I'd like to see an indication that a scan was 0 in this graphic preview:

<img width="815" alt="Screenshot 2023-08-22 at 5 20 32 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/50c62184-c1d3-4ec2-b36b-ce6ba5cc7480">

Maybe we could have the smallest bar (representing 1) in green. Then on hover it shows "0 errors"

### Tasks
- [ ] Please check if Adam agrees and action if yes

Thanks!

**Comment by tiagov8** [comment]
cc @jaydenalchin 

Hi @tombui99 

As per our conversation on Teams, here is the suggested UI:

- [ ] 1. Add a `#eeeeee` bar as default, so no errors shows a full light grey bar
- [ ] 2. Reduce the number of bars from 10 to 8 for a cleaner view


<img width="1036" alt="Screenshot 2023-09-04 at 1 05 28 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/ead720e2-d400-4e38-8e8f-b1d69d818d14">

Cheers,

**Comment by tombui99** [comment]
cc @tiagov8 @jaydenalchin @adamcogan @william-liebenberg @zacharykeeping @Jord-Gui 

>  Add a #eeeeee bar as default, so no errors shows a full light grey bar
Reduce the number of bars from 10 to 8 for a cleaner view
Make the columns' height slighter smaller (~ 120px)

All done - charts UI has been fixed as requested!

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/22a98a5d-6c53-4353-95e5-6af7631cfbc0)
