### ISSUE TITLE
♻️ UI/UX - Improve Responsive view

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#612]
Cc: @adamcogan @william-liebenberg @bradystroud @jaydenalchin @tiagov8 @zacharykeeping @Jord-Gui 

### Pain

Current responsive view is very clunky and unreadable

### Tasks

- [x] Fix and improve responsive views on all pages
- [x] Get feedback from designers @tiagov8 and @jaydenalchin 

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/2ff5185d-27c0-436a-998c-0bda33521a20)

**Figure: Current homescreen mobile view**

Thanks!

**Comment by zacharykeeping** [comment]
Hey @tiagov8 
cc: @jaydenalchin 

I've made a bunch of tweaks across the site to help improve the design and usability at smaller screen sizes, which are all live now.

- [ ] Can you please have a look and provide some feedback for where this could be further improved?

Thanks!

**Comment by tiagov8** [comment]
Hey @zacharykeeping 

As per our conversation on Teams, the biggest problem was the menu area which has been fixed already.
I am happy with the responsive view of the site on mobile.

<img width="814" alt="Screenshot 2023-09-19 at 4 01 11 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/3aeebe16-d1c4-4f3f-8cca-5672bfbfcb4a">

**Figure: Menu area fixed**

**Comment by zacharykeeping** [comment]
Done all - the mobile view seems to be in a good state currently.
