### ISSUE TITLE
♻️ UI - Implement Scan Results design feedback

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#654]
Cc: @tombui99 @william-liebenberg @tiagov8 @adamcogan 

Hi 

As per my conversation with @tiagov8, he had some feedback about the Scan Results page that we should implement.

The main issue is the unintuitive Ignore (🚫) button on broken links, which should be made into a checkbox in a new column "Ignore". This should open the Ignore URL modal as usual and then be marked as checked afterwards.

He also noted that once a URL is marked as ignored, this action can't be undone in the current UI. This should be updated so this can be reverted easily.

### Tasks

- [x] Move the ignore 🚫 button into checkbox in a new "Ignore" column
- [x] Make the Ignore column the last one
- [x] Allow this new checkbox to be undone in the UI
- [x] Remove the extra space before broken link URLs
- [x] Update the uses of css class .text-gray-600 to be #797979
- [x] Update the uses of css class .text-gray-800 to be #333333
- [x] Update the red bar's background colour to be #cc4141

### Screenshots

![62a229a8-6ee4-4afc-89b0-78ff40b9e7cb](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/f337c8da-94bd-47e0-a261-4fbaf16b5ccd)

**Figure: Button to move into a checkbox in a new Ignore column**

![9173874b-3030-45ab-ab08-bf04de43b6c2](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/45d4e485-d9f7-4476-865d-50666c38fcf9)

**Figure: Extra space to remove on broken links**

![b572821c-5a63-42f2-9396-6cbb8668ba3d](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/f4497e24-4f1d-4b6c-9594-b8af73204944)

**Figure: Red bar that should be changed to #cc4141**

Thanks!

**Comment by zacharykeeping** [comment]
Done all - the ignore functionality has been improved and the other design tweaks have been implemented.

<img width="1008" alt="Screenshot 2023-09-20 at 2 29 53 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/ec0b5695-5a6f-47d0-a352-0c8d5b494498">

**Figure: New checkbox column for Ignore**

<img width="1009" alt="Screenshot 2023-09-20 at 2 30 27 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/d9b6d940-8bd8-40d6-86d7-676f70319e77">

**Figure: Tweaked colours to be more consistent with company colours**
