### ISSUE TITLE
✨ Custom rule - Check phone numbers without links

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#694]
Cc: @adamcogan @william-liebenberg @tiagov8 @zacharykeeping 

  
### Pain

As per my conversation with @tiagov8 , we should add a new custom rule to find phone numbers without links within the sites.
See https://www.ssw.com.au/rules/do-you-know-to-hyperlink-your-phone-numbers/

### Tasks

- [x] Create a new custom rule that can find phone numbers without links

Thanks!

**Comment by zacharykeeping** [comment]
Done - a new rule has been created for this called "Content - Phone numbers must be in hyperlinks".

**Comment by tiagov8** [comment]
Hi @tombui99 

- [ ] 1. Can you make CodeAuditor ignore phone number inside code blocks?

...this way the SSW Rule https://www.ssw.com.au/rules/do-you-know-to-hyperlink-your-phone-numbers/ doesn't fail on its on rule :)

**Comment by tiagov8** [comment]
Hey @tombui99 

CodeAuditor caught these numbers which aren't phone numbers...

https://www.ssw.com.au/rules/power-platform-versioning/

<img width="1125" alt="Screenshot 2023-10-20 at 3 06 07 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/38eca435-ca02-4923-975f-793e89e47745">

- [ ] 1. Please rewrite the rule so you can avoid this false positives

**Comment by tiagov8** [comment]
Hi @tombui99 

Another weird false positive happened in this rule link: https://www.ssw.com.au/rules/rules-to-better-timesheets/

- [ ] 1. Please rewrite the rule so you can avoid these false positives

<img width="974" alt="Screenshot 2023-10-20 at 3 10 03 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/a90e6f2a-6d72-4b60-bb72-b93baee6d02c">

<img width="1140" alt="Screenshot 2023-10-20 at 3 09 58 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/b7baafde-110c-4bfa-a5ca-5dd91d363f72">

**Comment by tiagov8** [comment]
Hi @tombui99 

More false positives on SSW.Website scan:

<img width="987" alt="Screenshot 2023-10-20 at 3 39 54 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/37358e98-b985-4406-b7e5-1fbdc6f55ca1">

**Comment by tiagov8** [comment]
Hey @tombui99 

On https://ssw.fr/contact-us/

This is also a false positive

- [ ] 1. Please fix

<img width="961" alt="Screenshot 2023-10-20 at 4 10 52 PM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/5fea3684-322b-4936-bb0d-84e1c4730cbc">



Cheers,
