### ISSUE TITLE
♻️ Group scans with similar Urls

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#696]
Cc: @adamcogan @william-liebenberg @zacharykeeping 

### Pain

Scans with similar Urls should be grouped regardless of having "www" in the front or in other formats.

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/58849b53-38e8-451f-b0d0-c3e93fda7d93)

### Tasks

- [x] Group scans with similar Urls
- [ ] Investigate apex vs subdomain name
- [ ] Each scannable site should have known alias to help with grouping

Thanks!

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg @zacharykeeping 

> Group scans with similar Urls

Done - Scans with similar Urls are now grouped

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/c6c0cd13-982c-491c-8f9c-b0de6cf72bfa)
