### ISSUE TITLE
♻️ Investigate custom rules with options

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#707]
Cc: @william-liebenberg @tombui99 

Hi team

### Pain

As per our discussion with @william-liebenberg earlier, we should investigate ways we could include our own custom rules with options. For example, can we have a rule that checks for the correct spelling of words, and have those words provided as an option instead of hardcoded in the rule?

### Tasks

- [ ] Investigate
- [ ] Implement solution

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @jaydenalchin 

I have added an initial UI that supports adding custom options to custom rules. However it needs further improvement.

1. Can you guys leave some feedback to the UI below

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/efff4906-5147-4334-a8ba-936944a7d690)

**Figure: Input textbox for custom rules that support custom options**

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/2f7005c7-5dd3-48fe-adf0-b321f83b2454)

**Figure: When an option was added**

**Comment by tombui99** [comment]
cc @zacharykeeping @jaydenalchin @william-liebenberg 

As from my conversation with @hveraus and @tiagov8 , we should make the following changes to the UI:
 
<img width="474" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/edcabebf-f514-4e44-bfd1-df51cb57dae2">

1. red - don't need the words "please note"
2. blue - Indent the edit box 
3. green - change the text to: "Enter country code in [2-digit ISO](https://www.iso.org/obp/ui/#search) (E.g. "AU" for Australia)"
4. green - make the font a bit smaller

**Comment by tombui99** [comment]
cc @william-liebenberg @adamcogan @zacharykeeping 

> Implement and Update UI from designers' feedback

All done - I have implemented and updated the UI for the feature that now enable customising HTML rules

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/864f925e-910c-4159-b699-13ae775862a9)

**Comment by tiagov8** [comment]
Hi @tombui99 

- [ ] 1. The greybox is not indented as requested
- [ ] 2. The greybox needs more padding on top and bottom
- [ ] 3. Remove the word "your"

**Comment by tombui99** [comment]
Hey @tiagov8 

> The greybox is not indented as requested
The greybox needs more padding on top and bottom
Remove the word "your"

All done - let me know if you have any other feedback

<img width="524" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/e651338b-e22a-4faf-81c6-e293289c0bf2">
