### ISSUE TITLE
♻️ Scan Results - Fix inconsistencies with Unscannable Links handling

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#718]
Cc: @tombui99 @william-liebenberg 

Hi team

### Pain

I noticed a few issues and inconsistencies with the current handling of Unscannable Links:

1. In Scan Results under the Links tab where we list any links from the scan that we consider unscannable, the Unscannable Links list that we use here is still using the old hardcoded list and not retrieving the latest list from the centralised API we have since created.
2. For that same section, it will only show if there are other broken links in the scan result that aren't part of the unscannable links, instead of always just showing if the scan contained unscannable links.
3. For our total counts of broken links, this also hasn't been updated to use the API to retrieve our Unscannable Links list, so this should be updated to not use the hardcoded list and give us a proper count.

### Tasks

- [x] Update the Unscannable Links section under scan results to retrieve the data from our API rather than the hardcoded list
- [x] Update this section to always display if it contains matching unscannable links, rather than just when other broken links also exist
- [x] Update the total broken link counts to use the Unscannable Links API and use the latest data

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/3222f1cb-b11f-423d-bf73-d39a49b6f534)

**Figure: Unscannable Links do not show if no other broken links exist in a scan result, and the total broken links include these unscannable links because it's not using the latest list**

Thanks!

**Comment by zacharykeeping** [comment]
Done - this has been fixed.
