### ISSUE TITLE
📝 Link to the landing page

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#757]
Cc: @william-liebenberg @adamcogan 

Hi @tombui99 @zacharykeeping 

We have a nice landing page
https://codeauditor.com/

lets link to it so people find it.
also links help SEO

```[tasklist]
### Tasks
- [x] Add a link to the GItHub action marketplace page https://github.com/marketplace/actions/codeauditor-workflow
- [x] Add a link from the repo
- [x] Think about other places that could use a link
```

<img width="1800" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/38869720/8a673916-f14f-49d5-ac41-d7a6c1499d97">

**Figure: No link to codeauditor.com**

Thanks!

**Comment by tombui99** [comment]
Closing as this PBI has been completed
