### ISSUE TITLE
♻️ UI - Refactor Homepage

### ISSUE THREAD

**Issue by Jord-Gui** [SSWConsulting/SSW.CodeAuditor#765]
Cc: @tiagov8 @adamcogan @zacharykeeping @william-liebenberg 

Hi @tombui99 

### Pain

As per my conversation with @tiagov8, the website design needs a few minor tweaks.

### Tasks

- [x] Add a full stop at the end of each blurb (not the headings)
- [x] Add padding to right-side of text section
- [x] Align images/texts

### Screenshots

<img width="473" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/0416dd3b-4507-4bd1-903c-0d45d62976df">\
**Figure: No full stop at the end of paragraph**

<img width="566" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/7fe7bf74-957e-45c2-a2fa-40ef9942e7b4">\
**Figure: No padding on right of text**

<img width="1327" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/41951199/f88a42c6-3825-4b95-ac1c-434c24cb2517">\
**Figure: Images and text not aligned**

Thanks!

**Comment by tiagov8** [comment]
see https://www.sswdory.com/ for reference

**Comment by tombui99** [comment]
cc @adamcogan @tiagov8 @william-liebenberg @Jord-Gui 

> Add a full stop at the end of each blurb (not the headings)
 Add padding to right-side of text section
 Align images/texts

All done - UI has been fixed as requested

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/cc694702-b3aa-4dd8-81b6-72822ec7631e)
