### ISSUE TITLE
📝 Documentations - Add Case Studies and Testimonials to landing page

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#845]
Cc: @bradystroud @william-liebenberg @adamcogan @tiagov8 

### Pain

As from @bradystroud email task, we should add Case Studies and Testimonials to CodeAuditor's landing page.

### Suggested Documentation

In order to effectively promote CodeAuditor to potential clients, it is imperative that the landing page encapsulates narratives elucidating its positive impact on various projects. Incorporating testimonials and/or case studies would serve this purpose adeptly 🤖.

### Tasks

- [ ] Testimonials - Investigate to add these to CodeAuditor?
- [x] Case studies - Investigate to add these to CodeAuditor?
- [x]  Check analytics to see if these pages get many views (We already have case studies on ssw.com.au)
(https://ssw.com.au/company/clients)
- [x] Work on adding these to the CodeAuditor landing page

Thanks!

**Comment by tombui99** [comment]
As per my conversation with @william-liebenberg , we need to add "Case Study" breadcrumb and tab

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/fc59cd88-e02d-4e94-96d0-ee4b61693128)

**Comment by tombui99** [comment]
Cc: @bradystroud @william-liebenberg @adamcogan @tiagov8

> Case studies - Investigate to add these to CodeAuditor?
Work on adding these to the CodeAuditor landing page
Fixed UI from designers and PO's feedback

All done - I have added the case study page to CodeAuditor website with all the UI feedback implemented
See https://codeauditor.com/about and https://codeauditor.com/about/case-study/ssw
