### ISSUE TITLE
✨ Custom Rule - favicon must be added to a website

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#853]
Cc: @adamcogan @william-liebenberg @tiagov8 

  
### Pain

As per my conversation with @tiagov8 , we need to add a new custom rule that checks if a website has favicon.

See SSW Rule https://www.ssw.com.au/rules/favicon/

### Tasks

- [x] Implement the new rule

Thanks!

**Comment by tombui99** [comment]
Cc: @adamcogan @william-liebenberg @tiagov8 

> Implement the new rule 

Done - I have added a new custom rule to CodeAuditor that checks for website without favicon.
CodeAuditor scans for any website without `rel="icon`

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/9883def2-cc1d-44cb-b3f5-b088a3ba8000)

**Figure: New custom rule on CodeAuditor page https://codeauditor.com/rules**

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/c3d6fc72-754f-476a-93b5-3c713c13b0d8)

**Figure: Custom rule logic**

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/f02324a4-13f4-45ec-92bb-66d927ea81b0)

**Figure: All custom rules unit tests which have all passed**

**Comment by tiagov8** [comment]
Hi @tombui99 

One question:

1. Does the logic say the `rel="icon` should be inside the `<head>` ?

Before you close this Issue, we need some testing:

- [ ] 1. Please run CodeAuditor on https://ssweagleeye.com/ and confirm it catches the missing favicon
- [ ] 2. Then run on https://sugarlearning.com/ and confirm it doesn't give a false positive or something like that

**Comment by tombui99** [comment]
cc @william-liebenberg @adamcogan 

Hi @tiagov8 

From my testing, it is not technically possible to implement this custom rule due to how the HTML engine works. 
The engine checks each HTML element individually and reports if it finds a problem within that element. For example, within a `head`, there might be multiple `link` tags without the text `icon`, and the engine will report all of these tags, even if there's one correct tag with icon.
Therefore, I'm disabling the custom rule and closing this issue.
Let me know if there's anything.

**Comment by tombui99** [comment]
> Fix custom rule so it checks for `rel=icon` is used at least once in the `head`

Done - As approved by @william-liebenberg , we have implemented the custom rule with the workaround.
