### ISSUE TITLE
✨ New Rule - Emojis having spaces

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.CodeAuditor#863]
Cc: @adamcogan @tiagov8 

Hi @tombui99 
  
### Pain
I just noticed that a rule I edited didn’t have spaces between emojis and text.
https://www.ssw.com.au/rules/turn-emails-into-pbis/

### Suggested Solution
Add a rule to check to ensure emojis have spaces afterwards

### Tasks

- [ ] Investigate

### Screenshots
![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/79821522/aa0e2518-f60a-4719-a53c-34d6c5dc4f99)
**Figure: No spaces on emojis in this rule should be caught by CodeAuditor**

Thanks!

**Comment by tiagov8** [comment]
cc @adamcogan 

Hi @piers-sinclair 

❌ This Issue is technically **wrong** !

The example you used is an image via CSS class "good"... IT IS NOT an emoji!

This CANNOT be caught by CodeAuditor, since it isn't a HTML space, but CSS margin

- [ ] 1. Please make sure you understand the above
- [ ] 2. Please read this email thread: **Re: Spaces needed after emojis** 
- [ ] 3. Please read my comment on other Issue: https://github.com/SSWConsulting/SSW.CodeAuditor/issues/443 
- [ ] 4. Close this Issue
