### ISSUE TITLE
✨ New Rule - Okay -> ok

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.CodeAuditor#864]
Cc: @adamcogan @tiagov8 

Hi @tombui99 
  
### Pain
I just noticed that a rule I edited didn’t had "okay" example instead of "ok example"
https://www.ssw.com.au/rules/turn-emails-into-pbis/

### Suggested Solution
Check for okay -> ok

### Tasks

Make sure CodeAuditor checks for 

- [ ] "okay" and "Okay"; and suggests changing to "OK"
- [ ] "Ok" (lowercase "k"); and suggests changing to "OK"
- [ ] "O.K" or "o.k" or "O.k" (with a dot in any casing); and suggests changing to "OK"

### Screenshots
![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/79821522/9ac44fdc-2562-454c-a150-eca7f9e7143d)
**Figure: "Okay" should be flagged by CodeAuditor**

Thanks!

**Comment by tiagov8** [comment]
FYI - This is already in https://www.ssw.com.au/rules/avoid-common-mistakes/

**Comment by tiagov8** [comment]
Hi @piers-sinclair 

FYI your task "[ ] investigate" was vague, so I updated your comment to make it crystal clear :)

**Comment by tombui99** [comment]
cc @adamcogan @william-liebenberg @tiagov8 

Hey @piers-sinclair 

> Make sure CodeAuditor checks for
 "okay" and "Okay"; and suggests changing to "OK"
 "Ok" (lowercase "k"); and suggests changing to "OK"
 "O.K" or "o.k" or "O.k" (with a dot in any casing); and suggests changing to "OK"

Done - I have added checks for these terms in CodeAuditor.

I have also ran a scan with this checks on SSW Rules and found multiple locations where "OK" is used incorrectly

See https://codeauditor.com/htmlhint/00fb44cf-0e7a-4a5c-1f85-27a2aca96ff8?displayMode=1

**Comment by tiagov8** [comment]
Hi Tom,

Thanks for doing that

- [ ] 1. Please add a screenshot of the latest report showing the "Okay" on Piers image above was successfully caught by CodeAuditor
- [ ] 2. Fix that "Okay" to "OK" (Paste the link the PR for this change here)

**Comment by tombui99** [comment]
cc @adamcogan @piers-sinclair 

Hey @tiagov8 

> Please add a screenshot of the latest report showing the "Okay" on Piers image above was successfully caught by CodeAuditor

Done - Screenshot added in previous comment

> Fix that "Okay" to "OK" (Paste the link the PR for this change here)

Done - PR has been made to fix from "Okay" to "OK"
See https://github.com/SSWConsulting/SSW.Rules.Content/pull/8336

> Please tell us how many errors about this new "OK" rule?

There are 19 instances found on SSW Rules with this new "OK"

I have made a new PR that fixes all of them

See https://github.com/SSWConsulting/SSW.Rules.Content/pull/8337
