### ISSUE TITLE
♻️ Link Scan - Add default throttle and configure parameter

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#886]
Cc: @william-liebenberg @wicksipedia @adamcogan 

### Pain

As from @wicksipedia email, last week CodeAuditor brought down SSW Website as it was sending too many http requests in a short period of time. Therefore, we need to add default throttle and delay to make CodeAuditor run slower so these sites can catch a breath.

### Tasks

- [x] Add default throttle setting and scan delay to link scanning
- [x] Add an extra parameter to set max thread in CodeAuditor Action
- [x] Update Homepage instruction for the new setting

Thanks!

**Comment by tombui99** [comment]
cc @william-liebenberg @wicksipedia @adamcogan 

> Add default throttle setting and scan delay to link scanning

Done - added default maximum number of Golang thread to 100 and 3ms delay after scanning on each link

> Add an extra parameter to set max thread in CodeAuditor Action

Done - added new parameter in CodeAuditor workflow to set max Golang thread

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/1467e1e3-850f-4144-8a89-82cdae89f020)

**Figure: New input parameter to add max thread**

> Update Homepage instruction for the new setting

Done - added instruction on "How to run a scan" page to set max Golang thread

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/aeba00bf-8877-406d-baf8-6a98885bf7ee)

**Figure: New instruction to add optional setting**
