### ISSUE TITLE
✨ Load Test - Switch from Artillery to k6

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#900]
Cc: @GordonBeeming @william-liebenberg @zacharykeeping @adamcogan 

  
### Pain

As per my conversation with @william-liebenberg and @GordonBeeming , we should switch from using Artillery to k6 for performing load test. This is mainly because Artillery cannot perform test on Azure hosted sites that has Affinity setting enabled. 

### Suggested Solution

Remove Artillery load testing and its related dataset, and add k6 to do load testing. See https://grafana.com/docs/k6/latest/set-up/install-k6/ for k6 setup instructions.

### Tasks

- [ ] Remove Artillery Load Test and its instances from both UI and backend
- [ ] Remove [Why Artillery Load Test might fail on your URL and how you can fix it](https://github.com/SSWConsulting/SSW.CodeAuditor/wiki/SSW-CodeAuditor-Knowledge-Base-(KB)#why-artillery-load-test-might-fail-on-your-url-and-how-you-can-fix-it) section in the KB 
- [ ] Add k6 for load testing
- [ ] Replace Artillery instances in the UI and API with K6 (old scans with Artillery should still display its results)

Thanks!

**Comment by zacharykeeping** [comment]
Done - Tom finished this off.

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/02b1c61d-d5e8-4975-9147-b78000b8f61a)

**Figure: New console box result with k6 load test**

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/8f835493-122e-4fb4-a549-fc34a21d2dae)
**Figure: k6 load test result**
