### ISSUE TITLE
👷 CI/CD | Move to gated deployments

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#913]
### Pain

Currently we have a convoluted build and deployment story which requires merging pull requests to the staging branch to first deploy the staging site, and then merging the staging branch to main to do a production deployment.

### Suggested Solution

We should update this to use gated deployments with gates for Staging then Production on main and remove the existing staging branch workflow.

### Tasks

- [ ] Update the GitHub workflows to use a single workflow triggered on main that does gated deployments for Staging then Production
- [ ] Remove the staging branch
- [ ] Update the docs

Thanks!
