### ISSUE TITLE
♻️ API | Migrate from deprecated azure-storage package

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#918]
Hi team

### Pain

We're currently using the ```azure-storage``` npm package (https://www.npmjs.com/package/azure-storage?activeTab=readme) in our API. This package has been deprecated and should be updated to use @azure/storage-blob and @azure/data-tables instead.

### Tasks

- [ ] Install @azure/storage-blob and @azure/data-tables
- [ ] Refactor to use these new packages
- [ ] Remove azure-storage

Thanks!
